{
 "title": "Cassandra Overview (1.12)",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(cpus_system_time_secs{service_name=\"cassandra\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(mem_total_bytes{service_name=\"cassandra\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Disk" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(disk_used_bytes{service_name=\"cassandra\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Throughput - Write requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_mean",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Throughput - Write requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_mean",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Latency - Write response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_mean > 0 ",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Latency - Read response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_read_mean > 0 ",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_storage_load",
     "legendFormat": "{{task_name}} - {{host}} "
    }
   ]
  }
 ]
}