{
 "title": "DC/OS (1.12)",
 "description": "Example of an Alert Center for DC/OS 1.12",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 } },
  { "title": "Cluster Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_cpus_used)" }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_mem_used)" }
   ]
  },
  {
   "title": "Disk Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_disk_used)" }
   ]
  },
  {
   "title": "Cluster CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "max (mesos_master_cpus_percent)"
    }
   ]
  },
  {
   "title": "Cluster Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "max (mesos_master_mem_percent)" }
   ]
  },
  {
   "title": "Cluster Storage Allocation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "max (mesos_master_disk_percent)"
    }
   ]
  },
  { "title": "Mesos Master State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Master Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    { "expr": "min (mesos_master_uptime_secs)" }
   ]
  },
  {
   "title": "Masters Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "max by (host) (mesos_master_elected)",
     "legendFormat": "Elected"
    },
    {
     "expr": "max by (host) (mesos_master_uptime_secs)"
    },
    {
     "expr": "max by (host) (mesos_registrar_log_recovered)"
    },
    {
     "expr": "max by (host) (mesos_registrar_log_ensemble_size)"
    }
   ]
  },
  {
   "title": "Master Elected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_elected)" }
   ]
  },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round (min (mesos_registrar_log_ensemble_size) / 2, 1)"
    }
   ]
  },
  { "title": "Mesos Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Active Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_slaves_active)"
    }
   ]
  },
  {
   "title": "Inactive Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_slaves_inactive)"
    }
   ]
  },
  {
   "title": "Disconnected Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_slaves_disconnected)"
    }
   ]
  },
  {
   "title": "Unreachable Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_slaves_unreachable)"
    }
   ]
  },
  {
   "title": "CPU Usage % (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mesos_system_load_1min * 100", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Memory Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (host)(mesos_system_mem_total_bytes - mesos_system_mem_free_bytes)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Used Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum by(host)(disk_used)", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "Mesos Frameworks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Active Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (mesos_master_frameworks_active)"
    }
   ]
  },
  {
   "title": "Inactive Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (mesos_master_frameworks_inactive)"
    }
   ]
  },
  {
   "title": "Disconnected Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (mesos_master_frameworks_disconnected)"
    }
   ]
  },
  { "title": "Mesos Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Tasks Staging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_tasks_staging)"
    }
   ]
  },
  {
   "title": "Tasks Starting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_tasks_starting)"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_tasks_running)"
    }
   ]
  },
  {
   "title": "Tasks Killing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_tasks_killing)"
    }
   ]
  },
  {
   "title": "Tasks Errored",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_tasks_error)" }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (mesos_master_tasks_failed)"
    }
   ]
  },
  {
   "title": "Tasks Lost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max (mesos_master_tasks_lost)" }
   ]
  }
 ]
}