{
 "title": "Cassandra Overview (1.11)",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Node State",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_storage_load",
     "legendFormat": "{{task_name}} - {{host}} "
    }
   ]
  },
  {
   "title": "Errors and Overruns",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_storage_exceptions)",
     "legendFormat": "Storage Exceptions"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_commitlog_completedtasks)",
     "legendFormat": "Commit: Completed Tasks"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_commitlog_pendingtasks)",
     "legendFormat": "Commit: Pending Tasks"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_compaction_completedtasks)",
     "legendFormat": "Compaction: Completed Tasks"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_compaction_pendingtasks)",
     "legendFormat": "Compaction: Pending Tasks"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "min(cpus_limit{framework_name=\"cassandra\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "rate(cpus_system_time{framework_name=\"cassandra\"}[2m]) + rate(cpus_user_time{framework_name=\"cassandra\"}[2m])",
     "legendFormat": "CPU Usage {{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(mem_limit{framework_name=\"cassandra\"})",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "mem_total{framework_name=\"cassandra\"}",
     "legendFormat": "Memory Usage {{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Disk" }
   ],
   "targets": [
    {
     "expr": "min(disk_limit{framework_name=\"cassandra\"})",
     "legendFormat": "Disk Limit"
    },
    {
     "expr": "disk_used{framework_name=\"cassandra\"}",
     "legendFormat": "Disk Usage {{hostname}}"
    }
   ]
  },
  {
   "title": "Throughput - Write requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_m1_rate > 0",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Throughput - Read requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_read_m1_rate",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Latency - Write response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_mean",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Latency - Read response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_read_mean",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Key Cache - Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_cache_hitrate_keycache * 100",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "JVM GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_parnew_time{task_name=~\"node-.*-server\"}[5m]) + irate(jvm_gc_concurrentmarksweep_time{task_name=~\"node-.*-server\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}